/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogl_prj2;

import RenderManagement.JavaRenderer2;
import com.jogamp.opengl.awt.GLCanvas;
import com.jogamp.opengl.util.FPSAnimator;
import java.awt.BorderLayout;

/**
 *
 * @author Ivan
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonTurnLeft = new javax.swing.JButton();
        jButtonTurnRight = new javax.swing.JButton();
        jButtonTurnUp = new javax.swing.JButton();
        jButtonTurnDown = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(810, 650));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Вид Горшочка");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 34));
        jLabel1.setMinimumSize(new java.awt.Dimension(64, 34));
        jLabel1.setPreferredSize(new java.awt.Dimension(64, 34));
        jPanel5.add(jLabel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Деревянный", "Глиняный" }));
        jComboBox1.setAlignmentX(0.0F);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1);

        jPanel4.add(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Горшочек", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Цветочек", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jButtonTurnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogl_prj2/77_Essential_Icons_Reply.png"))); // NOI18N
        jButtonTurnLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTurnLeftMouseClicked(evt);
            }
        });
        jButtonTurnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnLeftActionPerformed(evt);
            }
        });
        jButtonTurnLeft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonTurnLeftKeyPressed(evt);
            }
        });
        jPanel7.add(jButtonTurnLeft);

        jButtonTurnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogl_prj2/77_Essential_Icons_Forward.png"))); // NOI18N
        jButtonTurnRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTurnRightMousePressed(evt);
            }
        });
        jButtonTurnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnRightActionPerformed(evt);
            }
        });
        jButtonTurnRight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonTurnRightKeyPressed(evt);
            }
        });
        jPanel7.add(jButtonTurnRight);

        jButtonTurnUp.setText("Вверх");
        jButtonTurnUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonTurnUpMouseReleased(evt);
            }
        });
        jButtonTurnUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonTurnUpKeyPressed(evt);
            }
        });
        jPanel7.add(jButtonTurnUp);

        jButtonTurnDown.setText("Вниз");
        jButtonTurnDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonTurnDownMouseReleased(evt);
            }
        });
        jButtonTurnDown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonTurnDownKeyPressed(evt);
            }
        });
        jPanel7.add(jButtonTurnDown);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogl_prj2/77_Essential_Icons_Minus.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogl_prj2/77_Essential_Icons_Plus.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 71, Short.MAX_VALUE))
        );

        MyOPENGL_activation();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MyOPENGL_activation() {
        renderGLCanvas = new GLCanvas();
        RenderManagement.RenderManager.renderContext= RenderManagement.RenderManagementState.PYRMYD;
        theRenderingLogic = new JavaRenderer2();
        renderGLCanvas.addGLEventListener(theRenderingLogic);
        jPanel1.add(renderGLCanvas, BorderLayout.CENTER);
        //rotation is performed only on each redraw. Animator runs display() in cycle:
        // https://www.tutorialspoint.com/jogl/jogl_rotation.htm
        animator = new FPSAnimator(renderGLCanvas, 300, true);
        animator.start();
    }
    
    private void jButtonTurnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnLeftActionPerformed
        
        //System.out.println("kb1!");
    }//GEN-LAST:event_jButtonTurnLeftActionPerformed

    private void jButtonTurnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnRightActionPerformed
        
        //System.out.println("kb2!");
    }//GEN-LAST:event_jButtonTurnRightActionPerformed

    private void jButtonTurnLeftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonTurnLeftKeyPressed
        theRenderingLogic.rotateT-=0.5f;        
    }//GEN-LAST:event_jButtonTurnLeftKeyPressed

    private void jButtonTurnRightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonTurnRightKeyPressed
        theRenderingLogic.rotateT+=0.5f;
    }//GEN-LAST:event_jButtonTurnRightKeyPressed

    private void jButtonTurnLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnLeftMouseClicked
        theRenderingLogic.rotateT-=0.5f;        
    }//GEN-LAST:event_jButtonTurnLeftMouseClicked

    private void jButtonTurnRightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnRightMousePressed
        theRenderingLogic.rotateT+=0.5f;
    }//GEN-LAST:event_jButtonTurnRightMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        theRenderingLogic.scaleFactor+=0.1f;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        theRenderingLogic.scaleFactor-=0.1f;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Integer selectedPotIndex = jComboBox1.getSelectedIndex();
        System.out.println(selectedPotIndex);
        switch (selectedPotIndex) {
            case 1: {
               RenderManagement.RenderManager.renderContext = RenderManagement.RenderManagementState.SQUARE_POT;
               theRenderingLogic.myRenderManagementUtil.cacheSquarePot();
               theRenderingLogic.myRenderManagementUtil.checkCurrentCachedData();
               break;
            }
            case 2: {
               RenderManagement.RenderManager.renderContext = RenderManagement.RenderManagementState.CLAY_POT;
               theRenderingLogic.myRenderManagementUtil.cacheClayPot();
               theRenderingLogic.myRenderManagementUtil.checkCurrentCachedData();
               break;
            }
            case 0:
            default: {
                RenderManagement.RenderManager.renderContext = RenderManagement.RenderManagementState.PYRMYD;
               break;
            }
                
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonTurnUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonTurnUpKeyPressed
        theRenderingLogic.rotateV-=0.5f;
    }//GEN-LAST:event_jButtonTurnUpKeyPressed

    private void jButtonTurnUpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnUpMouseReleased
        theRenderingLogic.rotateV-=0.5f;
    }//GEN-LAST:event_jButtonTurnUpMouseReleased

    private void jButtonTurnDownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTurnDownMouseReleased
        theRenderingLogic.rotateV+=0.5f;
    }//GEN-LAST:event_jButtonTurnDownMouseReleased

    private void jButtonTurnDownKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonTurnDownKeyPressed
        theRenderingLogic.rotateV+=0.5f;
    }//GEN-LAST:event_jButtonTurnDownKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    public GLCanvas renderGLCanvas;
    public FPSAnimator animator;
    public JavaRenderer2 theRenderingLogic;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonTurnDown;
    private javax.swing.JButton jButtonTurnLeft;
    private javax.swing.JButton jButtonTurnRight;
    private javax.swing.JButton jButtonTurnUp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
